language: node_js
deploy:
  provider: heroku
  api_key:
    secure: d9WawZsHP8IIsPlL0QbscapZOVz1ljCXuLVGTekIXQ23fn6LrFdE4wRCtMq8f6tFoRBY0uXeUCVliO48yBqR0Naw3d7Vm9+z1k5SKzSvh11ldMiioSRkabI3ptssOx8QdIM3sTs34K2nE0tTkf+OsvoYfndPHSo8Zh3OKkyZeOZFu0F2Z8CN6PBIyAEIHdZdtoODgc7ZbqRy1RbLUt+PIcB1F1Km62xOZt5/L7VtImBJFBGbE3ud/fQwO49BQsPCIF9JIFgPrgW05TVZG8SthttEzqp458/evpfT5vLNXbbkQN2VphKC7+Xx52gPpxFX5BRthGgPYwM4X9Y9dTIYqJ/cVIJPKK133vlMcQzMgareYeYUeRo//WFK3sN4I6rVzDChXKVGlh9IpfFQEW+R7dCPBsb65Vz25am1XThlR8NMR0+5z0yK9lEncVa8mWfRwMWs2DcJyoJP0h2mJiLJRTRrhQotk5pqXdVRQu2IVwmcmo5dArCRRkjseehJw+Rtj2Sb1lC5frHtgw2noOfSTp7pjqVYQymjo3uoHNiP5Iz+G4arXJjqeSzsZSI1dtvgkWaKS4PTcQQMjE0gEvqu081V/vWZmLDf1bPgrWrf+61xq0U8LtzWX9XgtH8DXBFpNUeTejUsdxfzcuFSPnk9IZ2CMBvWl5MzCOpVAJa81ME=
  app: sujithapp
  on:
    repo: sujith94/travis
